name: Eslatma
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  eslatma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kunlik eslatma
        run: python3 eslatma.py
        env:
          BOT_TOKEN: "8535445836:AAHkniWDqi25cLPDutKQY5valMv_naeQ1PI"
          CHAT_ID: "-800338592"
          SUPABASE_URL: "https://rztbawzfeqqtpbifkgjd.supabase.co"
          SUPABASE_KEY: "sb_publishable_mF63LJOpb_lzR_P_WmmZEA_W5oc8JPD"
